force-app/main/default/objects/Product2/fields/ProductExternalId__c.field-meta.xml
<CustomField>
    <fullName>ProductExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>A 13 digit unique identifier of each product. This field should be used to relate the Product2 and respective ProductHistory__c record.</description>
    <externalId>true</externalId>
    <inlineHelpText>A 13 digit unique identifier of each product. This field should be used to relate the Product2 and respective ProductHistory__c record.</inlineHelpText>
    <label>Product External Id</label>
    <length>13</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/SellingPrice__c.field-meta.xml
<CustomField>
    <fullName>SellingPrice__c</fullName>
    <description>A field reflecting the Product’s price.</description>
    <inlineHelpText>A field reflecting the Product’s price.</inlineHelpText>
    <label>Selling Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ProductHistory__c/ProductHistory__c.object-meta.xml
<CustomObject>
    <description>Replica of Product2 object records</description>
    <label>Product History</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductHistory__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is Product record is active.</description>
    <inlineHelpText>Is Product record is active.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProductHistory__c/fields/ProductExternalId__c.field-meta.xml
<CustomField>
    <fullName>ProductExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>A 13 digit unique identifier of each product. This field should be used to relate the Product2 and respective ProductHistory__c record.</description>
    <externalId>true</externalId>
    <inlineHelpText>A 13 digit unique identifier of each product. This field should be used to relate the Product2 and respective ProductHistory__c record.</inlineHelpText>
    <label>Product External Id</label>
    <length>13</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProductHistory__c/fields/SellingPrice__c.field-meta.xml
<CustomField>
    <fullName>SellingPrice__c</fullName>
    <description>A field reflecting the Product’s price.</description>
    <inlineHelpText>A field reflecting the Product’s price.</inlineHelpText>
    <label>Selling Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AP_TestDataFactory.cls
/**************************************************************************
Apex Class Name    : AP_TestDataFactory
Version            : 1.0 
Created Date       : 31/03/2021
Function           : Data factory class
----------------------------------------------------------------------------
* Developer             Date                   Description
* --------------------------------------------------------------------------                 
* Shubham Agrawal       31/03/2021             Original version
***************************************************************************/
public class AP_TestDataFactory {
    
    /************************************************************************************************
     * @Description - returns Product2 instance
     * @Parameters - String name, String code, Boolean isActive, String externalId, Decimal price
     * @Return Type - Product2 object instance
     */
	public static Product2 getProduct(String name, String code, Boolean isActive, String externalId, Decimal price) {
        return new Product2(
            Name = name,
            ProductCode = code,
            IsActive = isActive,
            ProductExternalId__c = externalId,
            SellingPrice__c = price
        );
    }
    
    /************************************************************************************************
     * @Description - returns ProductHistory__c instance
     * @Parameters - String name, Boolean isActive, String externalId, Decimal price
     * @Return Type - ProductHistory__c object instance
     */
    public static ProductHistory__c getProductHistory(String name, Boolean isActive, String externalId, Decimal price) {
        return new ProductHistory__c(
            Name = name,
            IsActive__c = isActive,
            ProductExternalId__c = externalId,
            SellingPrice__c = price
        );
    }
    
    /************************************************************************************************
     * @Description - returns User instance
     * @Parameters - String name, String profileName
     * @Return Type - User object instance
     */
    public static User getRunningUser(String name, String profileName) {
        
        if(String.isBlank(profileName) || String.isBlank(name)) return Null;
        
        String profileId = [SELECT Id FROM Profile WHERE Name = :profileName LIMIT 1]?.Id;
        
        return new User(
            LastName = name,
            Email = name + '@testemail.com',
            Username = name + '@testemail.com.test',
            ProfileId = profileId,
            EmailEncodingKey = 'UTF-8',
            Alias = name.substring(1,3),
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            LanguageLocaleKey = 'en_US'
        );
    }
}