force-app/main/default/objects/Product2/fields/ProductExternalId__c.field-meta.xml
<CustomField>
    <fullName>ProductExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>A 13 digit unique identifier of each product. This field should be used to relate the Product2 and respective ProductHistory__c record.</description>
    <externalId>true</externalId>
    <inlineHelpText>A 13 digit unique identifier of each product. This field should be used to relate the Product2 and respective ProductHistory__c record.</inlineHelpText>
    <label>Product External Id</label>
    <length>13</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProductHistory__c/ProductHistory__c.object-meta.xml
<CustomObject>
    <description>Replica of Product2 object records</description>
    <label>Product History</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductHistory__c/fields/ProductExternalId__c.field-meta.xml
<CustomField>
    <fullName>ProductExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>A 13 digit unique identifier of each product. This field should be used to relate the Product2 and respective ProductHistory__c record.</description>
    <externalId>true</externalId>
    <inlineHelpText>A 13 digit unique identifier of each product. This field should be used to relate the Product2 and respective ProductHistory__c record.</inlineHelpText>
    <label>Product External Id</label>
    <length>13</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AP_DisplayProductDetailsController.cls
/**************************************************************************
Apex Class Name    : AP_DisplayProductDetailsController
Version            : 1.0 
Created Date       : 01/04/2021
Function           : LWC controller class to display related Product2 details
					 on ProductHistory record page
----------------------------------------------------------------------------
* Developer             Date                   Description
* --------------------------------------------------------------------------                 
* Shubham Agrawal       01/04/2021             Original version
***************************************************************************/
public with sharing class AP_DisplayProductDetailsController {
    
    /************************************************************************************************
     * @Description - method to fetch related Product2 record Id based on ExternalId of 
     * ProductHistory record.
     * @Parameters - String productHistoryId
     * @Return Type - String - Product2 record Id
     */
    @AuraEnabled(cacheable=true)
    public static String getRelatedProductDetails(String productHistoryId){
        try {
            //get external id from the product history record
            String productExternalId = [SELECT ProductExternalId__c 
                                        FROM ProductHistory__c 
                                        WHERE Id = :productHistoryId
                                        WITH SECURITY_ENFORCED]?.ProductExternalId__c;
     
            if (String.isNotBlank(productExternalId)) {
                
                //get product2 id using product external id field value
                String product2Id = [SELECT Id 
                                     FROM Product2
                                     WHERE ProductExternalId__c = :productExternalId
                                     WITH SECURITY_ENFORCED]?.Id;
                if (String.isBlank(product2Id)) {
                    throw new AuraHandledException('No related product is available!');        
                } else {
                    return product2Id;
                }
            } else {
                throw new AuraHandledException('Incorrect Product External Id!');    
            }
        } catch (QueryException e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}